### ISSUE TITLE
Pushing peer review information into researcher's ORCID record

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/orcidProfile#150]
**Is your feature request related to a problem? Please describe.**
ORCID Members that are using Member's API have the possibility to adding peer review information into a researcher's ORCID record when they performed a review for a given journal that is an ORCID member.

However, currently the ORCID plugin for OJS/OPS doesn't allow that.

**Describe the solution you'd like**
Allow journals and preprint servers that are ORCID members to "push" peer review information into researcher's ORCID record following these instructions:

https://members.orcid.org/api/workflow/peer-review

**Comment by amandastevens** [comment]
One of PKP PS's hosted clients requested this feature as a way to incentivize reviewers to contribute to a journal. "Some journals have a hard time incentivizing reviewers and are wondering if the ORCID plugin can be used to ingest review metadata from OJS into ORCID. This might be an additional incentive to potential reviewers."

**Comment by mew2232** [comment]
We would love to have this feature to use across our OJS sites. Our student journals in particular find that offering recognition is key in attracting peer reviewers and Publons is not a good option for our program's size/budget. We would love to be able to utilize our ORCID membership through the same plugin that we use for authenticating author records so that we don't have to use our more than 1 of our 5 member API keys.

**Comment by withanage** [comment]
This issue was addressed in https://github.com/pkp/orcidProfile/issues/181.
Thus closing.
