### ISSUE TITLE
Enable users to login to OJS using their ORCID credentials?

### ISSUE THREAD

**Issue by devsoper** [pkp/orcidProfile#317]
**Is your feature request related to a problem? Please describe.**

Sort of - I receive lots of emails from authors and reviewers who forget how to log in to their OJS accounts. Usually they forget that their username is not their email address. This is frustrating for the authors and reviewers, as well as for editors at the journals and technical editors on my publishing team. Enabling users to login to OJS using their ORCID credentials could simplify this process for some users. 

**Describe the solution you'd like**

Many ORCID integrations enable users to log in to the integrated system using their ORCID credentials. If this could be presented as an option alongside the regular username / password fields on the OJS account login page for the journal, that would be ideal. 

**Describe alternatives you've considered**

**Additional context**

Apologies if the plugin already does this or this functionality has already been requested and y'all decided against it - I did review the plugin documentation and the readme here in Github and the existing issues and did not see anything that suggested the plugin currently does this.

**Comment by asmecher** [comment]
@devsoper, I think what you're looking for is the OpenID plugin -- available in the Plugin Gallery for 3.3.0 and prior. We've just about completed updates for 3.4.0-x, and have "patriated" the plugin into PKP's set of repositories, as the original author has moved on. I'll mark this issue closed, but please feel free to take a look at it and discuss [over on the openid repo](https://github.com/pkp/openid) (or, if it's a general question rather than a specific bug, the [PKP forum](https://forum.pkp.sfu.ca/)).
